# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - bash: echo Dev First Job
    - job: DevSeccond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo QA First Job
- stage: ProdDeploy
  dependsOn:
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job
