# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'
    windows:
      operatingSystem: 'windows'
pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Running on $(operatingSystem)
  displayName: 'Run a one-line script'